name: 🏁 Windows Builds

on:
  pull_request:
    branches: [main]

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    runs-on:  "windows-latest"
    name: ${{matrix.name}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - identifier: windows-debug
            name: Windows Debug
            target: template_debug
            platform: windows
            arch: x86_64
          - identifier: windows-release
            name: Windows Release
            target: template_release
            platform: windows
            arch: x86_64

      steps:
        - name: Install mingw64
          shell: sh
          run: |
            sudo apt-get install mingw-w64
            sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
            sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix

        - name: Set up Python
          uses: actions/setup-python@v2

        - name: Set up SCons
          shell: bash
          run: |
            python -c "import sys; print(sys.version)"
            python -m pip install scons
            scons --version

        - name: Checkout project
          uses: actions/checkout@v3
          with:
            submodules: recursive
        
        - name: Compile extension
          shell: sh
          run: |
            scons target='${{ matrix.target }}' platform='${{ matrix.platform }}' arch='${{ matrix.arch }}' -j2
  #         needs to be changed to your custom location
            ls -l game/bin/summator/
        
        - name: Delete compilation files
          run: |
            Remove-Item game/bin/summator/* -Include *.exp,*.lib,*.pdb -Force

        - name: Upload artifact
          uses: actions/upload-artifact@v3.1.1
          with:
            name: ${{ github.event.repository.name }}
            path: |
              ${{ github.workspace }}/game/bin/summator/